Vizzuality/gefc-api

README.md, app/controllers/api/v1/users.rb, app/models/widgets_importer.rb, app/services/api/v1/user_authenticator.rb, config/deploy.rb, spec/requests/api/v1/users_controller_spec.rb
Changed authorization to authentication,fixed widgets importer if default nil,added mastrky to deploy.
=> FIxs for widgets importer and credentials

app/controllers/api/v1/entities.rb
```
{"email":"valid_example@example.com","username":null,"role":"guest"}
```
=> Expose role in user info

app/controllers/api/v1/entities.rb
(separate endpoint exists to pull the records)
=> Removed records from indicator endpoint

.gitignore, Gemfile, Gemfile.lock, README.md, app/controllers/api/v1/entities.rb, app/controllers/api/v1/indicators.rb, app/models/indicator.rb, app/models/region.rb, config/environments/test.rb, spec/integration_helper.rb, spec/models/indicator_spec.rb, spec/models/region_spec.rb, spec/requests/api/v1/indicators_controller_spec.rb
- Added simplecon for coverage
- Added Regions endpoint to Indicators controller
=> Added Regions endpoint to Indicators controller

.gitignore, app/controllers/api/v1/users.rb, app/controllers/application_controller.rb, app/models/active_admin_adapter.rb, app/models/geometry_points_importer.rb, app/models/geometry_polygons_importer.rb, app/models/groups_importer.rb, app/models/user.rb, app/services/api/v1/find_or_upsert_indicator.rb, app/services/api/v1/user_authenticator.rb, app/services/api/v1/user_authorizator.rb, config/initializers/active_admin.rb, config/routes.rb
- Added "admin" as role to the User model.
- Modified api Authentication and api Authorization to allow downloads only to users with admin role.
- Modified routes and initializer to use ActiveAdminAdapter combined with ApplicationController when login with Devise in the AdminPanel.
- EXTRA: Added some output messages to the importers. You know, is always nice to see that something is happening and the server ain't broken.
=> Changed from AdminUser to User, and make download available only for admins.

app/controllers/api/v1/entities.rb, app/controllers/api/v1/indicators.rb, app/models/groups_importer.rb, app/models/indicator.rb, app/models/record.rb, app/models/scenario.rb, app/services/api/v1/find_or_upsert_scenario.rb, db/migrate/20210812125512_create_scenarios.rb, db/migrate/20210817130510_add_scenario_to_records.rb, db/schema.rb, spec/factories/scenarios.rb, spec/models/scenario_spec.rb
- Added Scenario and relationship with Records.
- Modified GroupsImporter to handle the presence of scenarios in the csv.
- Fixed duplication in the indicators endpoint route.
=> Added Scenario to Records and Indicators

app/controllers/api/v1/entities.rb, app/models/groups_importer.rb, app/models/indicator.rb, app/models/scenario.rb, app/services/api/v1/find_or_upsert_scenario.rb, db/migrate/20210824162444_add_translation_to_scenario.rb, db/schema.rb, spec/factories/scenarios.rb, spec/factories/users.rb, spec/integration_helper.rb, spec/models/indicator_spec.rb, spec/requests/api/v1/downloads_controller_spec.rb, spec/requests/api/v1/indicators_controller_spec.rb
https://vizzuality.atlassian.net/browse/GECHINA-155?atlOrigin=eyJpIjoiMzZmNDRiYjQ0MjE4NDAxMDkzN2MyMTcyMWVhNzY1YTUiLCJwIjoiaiJ9
- Made scenarios translatable.
- Exposed Scenarios for Indicators.
=> Update importer and Scenario to use translations

app/controllers/api/v1/users.rb, spec/requests/api/v1/users_controller_spec.rb
https://vizzuality.atlassian.net/browse/GECHINA-162?atlOrigin=eyJpIjoiOWE0OTEzZjA5MDg5NDA4M2I1MDE0ZDEyNjZkOTY1NTgiLCJwIjoiaiJ9
=> Added validation of current password before updating password

app/controllers/api/v1/groups.rb
The title speaks by itself. I added some eager loading to speed the request response.
=> Added some eager loading to the records query

app/models/indicator.rb, app/models/widgets_importer.rb, app/services/api/v1/find_or_upsert_indicator.rb, db/migrate/20211003084830_add_datasource_to_indicator.rb, db/migrate/20211003095820_add_download_privilege_to_indicators.rb, db/schema.rb
https://vizzuality.atlassian.net/browse/GECHINA-106
https://vizzuality.atlassian.net/browse/GECHINA-144
=> Added data source, download_privilege and description

app/controllers/api/v1/groups.rb, app/services/api/v1/filter_indicator_records.rb, spec/requests/api/v1/groups_controller_spec.rb, spec/services/api/v1/filter_indicator_records_spec.rb
https://vizzuality.atlassian.net/browse/GECHINA-194
=> Added filter records by visualization

app/controllers/api/v1/entities.rb, app/controllers/api/v1/indicators.rb, db/migrate/20211115174701_add_meta_to_indicators.rb, db/schema.rb, lib/tasks/indicators.rake
https://vizzuality.atlassian.net/browse/GECHINA-202
=> Added endpoint for indicators metadata

app/models/record.rb, db/migrate/20211130093110_change_units_to_nullable_to_records.rb, db/schema.rb, lib/tasks/records.rake
https://vizzuality.atlassian.net/browse/GECHINA-207
=> feature/GECHINA-207 Changed record unit to be nullable and changed importer to avoid crating nil unit

app/models/indicator.rb, app/models/record.rb, spec/models/indicator_spec.rb, spec/requests/api/v1/groups_controller_spec.rb, spec/requests/api/v1/indicators_controller_spec.rb
https://vizzuality.atlassian.net/browse/GECHINA-211
=> feature/GECHINA-211 Added scenario id to the response

app/models/indicator.rb
https://vizzuality.atlassian.net/browse/GECHINA-208
=> Fixed duplicated scenarios in meta indicators

Gemfile, Gemfile.lock, app/controllers/api/v1/api_cache_buster.rb, app/controllers/api/v1/groups.rb, app/controllers/api/v1/health.rb, app/controllers/api/v1/indicators.rb, app/controllers/api/v1/regions.rb
https://vizzuality.atlassian.net/browse/GECHINA-204
- Added Cache-control to the response headers to enable Varnish's caching.
=> Added response headers for health endpoint

app/controllers/api/v1/groups.rb, app/controllers/api/v1/indicators.rb, app/controllers/api/v1/regions.rb, app/services/api/v1/fetch_group.rb, app/services/api/v1/fetch_indicator.rb, app/services/api/v1/fetch_region.rb, app/services/api/v1/fetch_subgroup.rb, spec/requests/api/v1/indicators_controller_spec.rb
- Moved the caching logic to a single layer.
- Removed queries.
=> Simplified queries and caching

.env.sample, config/initializers/swagger.rb
https://vizzuality.atlassian.net/browse/GECHINA-218
=> feature/GECHINA-218 Configure swagger to work along varnish

app/models/indicator.rb, lib/tasks/indicators.rake
https://vizzuality.atlassian.net/browse/GECHINA-203
=> Feature/GECHINA-203 Added default_visualization to meta

app/controllers/api/v1/entities.rb, app/controllers/api/v1/indicators.rb, app/models/indicator.rb, spec/requests/api/v1/indicators_controller_spec.rb
https://vizzuality.atlassian.net/browse/GECHINA-205
=> Feature/GECHINA-205 Added filter by unit, year and region to sankey

app/controllers/api/v1/entities.rb, app/models/indicator.rb
https://vizzuality.atlassian.net/browse/GECHINA-214
=> Feature/GECHINA-214 Send access info with the indicators

app/controllers/api/v1/api_cache_buster.rb, app/models/indicator.rb, spec/integration_helper.rb, spec/requests/api/v1/groups_controller_spec.rb, spec/requests/api/v1/indicators_controller_spec.rb, spec/requests/api/v1/users_controller_spec.rb, spec/spec_helper.rb, spec/support/custom_matchers/json_matchers.rb
https://vizzuality.atlassian.net/browse/GECHINA-250
=> Fix/GECHINA-250  Fixed combined params for the sankey endpoint 

app/controllers/api/v1/entities.rb, app/controllers/api/v1/users.rb, app/workers/hard_worker.rb, db/migrate/20220425112426_add_name_organization_and_title_to_users.rb, db/schema.rb, spec/requests/api/v1/users_controller_spec.rb
https://vizzuality.atlassian.net/browse/GECHINA-271
=> GECHINA-271 Added name, organization and title to users
